import jsPDF from "jspdf";
import type {
  StatisticsSummary,
  HourlyStats,
  DailyStats,
} from "@/types/vision-detection";

export type ReportPeriod = "hourly" | "daily" | "biweekly" | "monthly";

export function downloadQualityReportPdf(
  summary: StatisticsSummary,
  data: HourlyStats[] | DailyStats[],
  period: ReportPeriod,
  dateRange: { start: string; end: string }
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let y = margin;

  const periodLabel =
    period === "hourly"
      ? "Hourly"
      : period === "daily"
        ? "Daily"
        : period === "biweekly"
          ? "Biweekly"
          : "Monthly";

  // --- Header ---
  doc.setFontSize(20);
  doc.setTextColor(0);
  doc.text("Brinex - Quality Inspection Report", margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, margin, y);
  y += 5;
  doc.text(
    `Period: ${periodLabel} | ${dateRange.start} to ${dateRange.end}`,
    margin,
    y
  );
  y += 10;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // --- Summary ---
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Summary", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setTextColor(60);
  const summaryLines = [
    `Total Detections: ${summary.totalDetections}`,
    `Average Purity: ${summary.averagePurity.toFixed(1)}%`,
    `Pure: ${summary.totalPure}  |  Impure: ${summary.totalImpure}  |  Unwanted: ${summary.totalUnwanted}`,
    `Detections/Hour: ${summary.detectionsPerHour.toFixed(1)}`,
  ];
  for (const line of summaryLines) {
    doc.text(line, margin, y);
    y += 6;
  }
  y += 6;

  // --- Data Table ---
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text(`${periodLabel} Breakdown`, margin, y);
  y += 8;

  // Column config
  const isHourly = period === "hourly";
  const colX = [margin, 55, 85, 115, 145, 170];
  const headers = isHourly
    ? ["Hour", "Detections", "Pure", "Impure", "Unwanted", "Avg Purity"]
    : ["Date", "Detections", "Pure", "Impure", "Unwanted", "Avg Purity"];

  // Table header
  doc.setFontSize(9);
  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  headers.forEach((h, i) => doc.text(h, colX[i], y));
  y += 2;
  doc.setDrawColor(180);
  doc.line(margin, y, pageWidth - margin, y);
  y += 5;

  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40);

  for (const row of data) {
    if (y > pageHeight - 30) {
      doc.addPage();
      y = margin;
      // Re-draw header on new page
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0);
      headers.forEach((h, i) => doc.text(h, colX[i], y));
      y += 2;
      doc.line(margin, y, pageWidth - margin, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(40);
    }

    const label = isHourly
      ? `${(row as HourlyStats).hour}:00`
      : (row as DailyStats).date;
    const cells = [
      label,
      String(row.detections),
      String(row.pureCount),
      String(row.impureCount),
      String(row.unwantedCount),
      `${row.avgPurity.toFixed(1)}%`,
    ];
    cells.forEach((c, i) => doc.text(c, colX[i], y));
    y += 6;
  }

  // --- Footer ---
  y = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    "Generated by Brinex Quality Inspection System",
    pageWidth / 2,
    y,
    { align: "center" }
  );

  // Save
  const dateStr = new Date().toISOString().split("T")[0];
  doc.save(`quality-report-${periodLabel.toLowerCase()}-${dateStr}.pdf`);
}
